import os 
from pathlib import Path
import logging 

logging.basicConfig(level=logging.INFO,
                    format="[%(asctime)s]: %(message)s")

project_name =  "sdlc_agents"
list_of_files = [
    ".github/workflows/.gitkeep",
    "src/__init__.py",
    f"src/{project_name}/__init__.py",
    f"src/{project_name}/main.py",
    f"src/{project_name}/config.py",
    f"src/{project_name}/state/__init__.py",
    f"src/{project_name}/state/schema.py",
    f"src/{project_name}/state/enums.py",
    f"src/{project_name}/a2a/__init__.py",
    f"src/{project_name}/a2a/message.py",
    f"src/{project_name}/a2a/summarizer.py",
    f"src/{project_name}/a2a/router.py",
    f"src/{project_name}/mcp_clients/__init__.py",
    f"src/{project_name}/mcp_clients/manager.py",
    f"src/{project_name}/mcp_clients/registry.py",
    f"src/{project_name}/mcp_clients/transports.py",
    f"src/{project_name}/mcp_clients/router.py",
    f"src/{project_name}/retrieval/service.py",
    f"src/{project_name}/retrieval/corpora/__init__.py",
    f"src/{project_name}/retrieval/corpora/base.py",    
    f"src/{project_name}/retrieval/corpora/live_code.py",
    f"src/{project_name}/retrieval/corpora/past_projects.py",
    f"src/{project_name}/retrieval/corpora/lib_docs.py",
    f"src/{project_name}/retrieval/corpora/patterns.py",
    f"src/{project_name}/retrieval/corpora/feedback.py",
    f"src/{project_name}/retrieval/embeddings/__init__.py",
    f"src/{project_name}/retrieval/embeddings/providers.py",
    f"src/{project_name}/retrieval/embeddings/selector.py",
    f"src/{project_name}/retrieval/chunking/__init__.py",
    f"src/{project_name}/retrieval/chunking/ast_chunker.py",
    f"src/{project_name}/retrieval/chunking/semantic_chunker.py",
    f"src/{project_name}/retrieval/chunking/section_chunker.py",
    f"src/{project_name}/retrieval/chunking/contextual.py",
    f"src/{project_name}/retrieval/retrievers/__init__.py",
    f"src/{project_name}/retrieval/retrievers/hybrid.py",
    f"src/{project_name}/retrieval/retrievers/reranker.py",
    f"src/{project_name}/retrieval/retrievers/query_expansion.py",
    f"src/{project_name}/retrieval/retrievers/agentic.py",
    f"src/{project_name}/retrieval/store/__init__.py",
    f"src/{project_name}/retrieval/store/qdrant_client.py",
    f"src/{project_name}/retrieval/store/schema.py",
    f"src/{project_name}/retrieval/events.py",
    f"src/{project_name}/retrieval/scheduler.py",
    f"src/{project_name}/retrieval/sources/__init__.py",
    f"src/{project_name}/retrieval/sources/github_fetcher.py",
    f"src/{project_name}/retrieval/sources/docs_fetcher.py",
    f"src/{project_name}/retrieval/sources/workflow_extractor.py",
    f"src/{project_name}/retrieval/cache.py",
    f"src/{project_name}/retrieval/types.py",
    f"src/{project_name}/retrieval/sources/workflow_extractor.py",
    f"src/{project_name}/agents/__init__.py",
    f"src/{project_name}/agents/base.py",
    f"src/{project_name}/agents/requirements_agent.py",
    f"src/{project_name}/agents/architect_agent.py",
    f"src/{project_name}/agents/developer_agent.py",
    f"src/{project_name}/agents/qa_agent.py",
    f"src/{project_name}/agents/devops_agent.py",
    f"src/{project_name}/agents/critic_agent.py",
    f"src/{project_name}/prompts/__init__.py",
    f"src/{project_name}/prompts/requirements.md",
    f"src/{project_name}/prompts/architect.md",
    f"src/{project_name}/prompts/developer.md",
    f"src/{project_name}/prompts/qa.md",
    f"src/{project_name}/prompts/devops.md",
    f"src/{project_name}/prompts/critic.md",
    f"src/{project_name}/prompts/retrieval/query_expansion.md",
    f"src/{project_name}/prompts/retrieval/contextual_blurb.md",
    f"src/{project_name}/memory/__init__.py",
    f"src/{project_name}/memory/short_term.py",
    f"src/{project_name}/memory/long_term.py",
    f"src/{project_name}/memory/artifacts.py",
    f"src/{project_name}/orchestrator/__init__.py",
    f"src/{project_name}/orchestrator/graph.py",
    f"src/{project_name}/orchestrator/edges.py",
    f"src/{project_name}/orchestrator/nodes.py",
    f"src/{project_name}/orchestrator/interrupts.py",
    f"src/{project_name}/orchestrator/subgraphs/__init__.py",
    f"src/{project_name}/orchestrator/subgraphs/developer_subgraph.py",
    f"src/{project_name}/hitl/__init__.py",
    f"src/{project_name}/hitl/api.py",
    f"src/{project_name}/hitl/schemas.py",
    f"src/{project_name}/hitl/events.py",
    f"src/{project_name}/hitl/dashboard/__init__.py",
    f"src/{project_name}/hitl/dashboard/__init__.py",
    f"src/{project_name}/evaluation/__init__.py",
    f"src/{project_name}/evaluation/retrieval/__init__.py",
    f"src/{project_name}/evaluation/retrieval/test_sets/__init__.py",
    f"src/{project_name}/evaluation/retrieval/test_sets/live_code.jsonl",
    f"src/{project_name}/evaluation/retrieval/test_sets/past_projects.jsonl",
    f"src/{project_name}/evaluation/retrieval/test_sets/lib_docs.jsonl",
    f"src/{project_name}/evaluation/retrieval/test_sets/patterns.jsonl",
    f"src/{project_name}/evaluation/retrieval/test_sets/feedback.jsonl",
    f"src/{project_name}/evaluation/retrieval/ragas_runner.py",
    f"src/{project_name}/evaluation/retrieval/metrics.py",
    f"src/{project_name}/evaluation/end_to_end/workflow_eval.py",
    f"src/{project_name}/observability/__init__.py",
    f"src/{project_name}/observability/tracing.py",
    f"src/{project_name}/observability/logging.py",
    f"src/{project_name}/observability/retrieval_telemetry.py",
    f"src/{project_name}/utils/__init__.py",
    f"src/{project_name}/utils/retries.py",
    f"src/{project_name}/utils/idempotency.py",
    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/unit/test_a2a_message.py",
    "tests/unit/test_state_schema.py",
    "tests/unit/test_chunking/__init__.py",
    "tests/unit/test_agents/__init__.py",
    "tests/integration/__init__.py",
    "tests/integration/test_mcp_connection.py",
    "tests/integration/test_graph_follow.py",
    "tests/integration/test_hitl_loop.py",
    "tests/integration/test_retrieval/__init__.py",
    "tests/e2e/test_full_sdlc.py",
    "scripts/__init__.py",
    "scripts/seed_memory.py",
    "scripts/seed_patterns.py",
    "scripts/rebuild_lib_docs.py",
    "scripts/replay_workflow.py",
    "scripts/run_retrieval_eval.py",
    "scripts/mcp_health_check.py",
    "docs/architecture.md",
    "docs/retrieval.md",
    "docs/adr/.gitkeep",
    "docs/runbook.md",
    "configs/mcp_servers.yaml",
    "configs/agents.yaml",
    "configs/memory.yaml",
    "configs/retrieval.yaml",
    "configs/libraries.yaml",
    "requirements.txt",
    ".env",
    ".env.example"]


for file_path in list_of_files:
    file_path =  Path(file_path)
    file_dir,file_name = os.path.split(file_path)

    if file_dir != "":
        os.makedirs(file_dir,exist_ok=True)
        logging.info(f"Creating directory: {file_dir} for file: {file_name}")

    if (not os.path.exists(file_path)) or (os.path.getsize(file_path) == 0):
        with open(file_path,"w") as f:
            pass
            logging.info(f"Creating an empty file: {file_path}")
    
    else:
        logging.info(f"{file_name} already exists")