from pathlib import Path
import subprocess

from src.core.config import settings
from src.agents.base_agent import BaseAgent
from src.models.schemas import Requirements
from src.pipelines.state import SDLCState
from src.tools.test_runner import TestRunner
from src.tools.llm_factory import LLMFactory

class QAAgent(BaseAgent):
    """Runs pytest against the generated codebase. 
    Tests are generated by the Developer Agent 
    as part of the codebase (simpler than a separate test-gen step)"""

    name = "qa_agent"

    def _process(self, state: SDLCState):
        if not state.get("codebase"):
            return {
                "test_report": {"status": "fail", "errors": ["Developer agent produced no codebase"], "passed": 0, "failed": 0, "raw_output": ""},
                "qa_retries": 0,
                "status": "qa_fail",
            }
        project_dir = Path(state["codebase"]["project_dir"])
        runner = TestRunner(project_dir)

        self._install_deps(project_dir)

        report = runner.run()

        retries = state.get("qa_retries",0) + (0 if report.status == "pass" else 1)

        return {"test_report":report.model_dump(),
                "qa_retries":retries,
                "status":f"qa_{report.status.value}"}

    def _install_deps(self,project_dir: Path) -> None:
        req = project_dir / "requirements.txt"
        
        if not req.exists():
            return 
        try:
            subprocess.run(["pip","install","-q","-r",str(req)],
                           timeout=120,
                           capture_output=True,
                           check=False)
        
        except Exception as e:
            self.logger.warning(f"Dependencies installation failed (continuing): {e}")





