from langchain_core.prompts import ChatPromptTemplate

CODE_REVIEW_PROMPT = ChatPromptTemplate.from_messages([
    ('system',
     'You are a senior staff engineer performing a rigorous code review of '
     'machine-generated code. Focus on: correctness against requirements, '
     'obvious bugs, security issues (injection, auth, secret handling), '
     'API misuse, missing error handling at boundaries, and absence of '
     'runnable tests. Do NOT nitpick style. Only flag issues that matter.\n\n'
     'DOC-GROUNDED REVIEW RULES (non-negotiable):\n'
     '- The "Retrieved documentation" block below was fetched from Context7 '
     'for the exact libraries in the stack and reflects their current stable '
     'releases. Use it as the source of truth.\n'
     '- Any API, decorator, import path, or config key in the generated code '
     'that is NOT evidenced by the retrieved docs is a failure — add a '
     'specific required_fix naming the file and the offending symbol.\n'
     '- Any dependency in requirements.txt that is unpinned, or pinned to a '
     'version different from what the retrieved docs indicate, is a failure. '
     'Add a required_fix telling the developer what to pin.\n'
     '- Ignore this rule only for libraries whose doc section reads '
     '"(no docs retrieved)".\n\n'
     'SPECIFIC BUG CHECKS (always run these, flag each hit with file+line):\n'
     '- pytest fixture injection: BEFORE flagging, READ the function\'s '
     'parameter list character-by-character. Only flag when the fixture '
     'name is GENUINELY ABSENT from the parameter list. Do NOT flag a '
     'test as missing a fixture parameter when the parameter is already '
     'there — even if the body also references the name. False '
     'positives here are worse than missed real bugs.\n'
     '- pytest async tests: if any `async def test_*` or '
     '`@pytest.mark.asyncio` appears in a test file, verify BOTH '
     '(a) `requirements.txt` contains `pytest-asyncio`, AND '
     '(b) a `pytest.ini` (or equivalent pyproject config) exists with '
     '`asyncio_mode` set. Flag missing pieces as HIGH severity with '
     'file+line pointing at the offending async test.\n'
     '- fastapi.testclient.TestClient: if any file imports TestClient, '
     'requirements.txt must list `httpx`. Flag if missing.\n'
     '- duplicate or mismatched imports against what the retrieved docs '
     'show (e.g. `from pydantic import BaseSettings` when docs show '
     '`from pydantic_settings import BaseSettings`).\n\n'
     'ISSUE LOCATION RULES (non-negotiable):\n'
     '- For EVERY entry in `issues`, populate BOTH the `file` field '
     '(exact relative path as shown in "Generated files") AND the `line` '
     'field (1-indexed line number within that file). Count lines from 1 '
     'at the top of the displayed file content.\n'
     '- If an issue spans multiple lines, point `line` to the first '
     'offending line.\n'
     '- If an issue is truly file-wide (e.g. "missing tests for this '
     'module"), still set `file` to the closest file and `line` to 1.\n'
     '- Never leave `line` null for an issue that references real code.\n\n'
     'When issues are found, set passed=false and produce a SHORT list of '
     'concrete, actionable required_fixes the developer can apply directly. '
     'When the code is acceptable as-is, set passed=true with an empty '
     'required_fixes list. Output ONLY the structured CodeReview object.'),
    ('human',
     'Requirements:\n{requirements_summary}\n\n'
     'Architecture:\n{architecture}\n\n'
     'Retry attempt: {retry_attempt}\n\n'
     'Retrieved documentation (authoritative):\n{docs_context}\n\n'
     'Generated files (path and content, lines are 1-indexed, content may be truncated):\n'
     '{files}\n\n'
     'Produce the CodeReview. Remember to populate file AND line for every issue.')
])
